# Generated by Django 4.1 on 2022-10-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0002_item_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="photo",
            field=models.ImageField(default="404.png", upload_to="items"),
            preserve_default=False,
        ),
    ]
