# Generated by Django 4.1 on 2022-11-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_native_name_remove_user_phone_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(null=True, upload_to="users"),
        ),
    ]
