# Generated by Django 4.1 on 2022-11-07 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
    ]
